### ISSUE TITLE
Integrate Swagger UI for Rest API

### ISSUE THREAD

**Issue by omssp** [abhikoreti/review-app#2]
Use and integrate [swagger.io](https://swagger.io/tools/swagger-ui/) for JSON rest API
Pointer to keep note
- swagger config should populate itself directly from routes file
- integrate into vercel builds

**Comment by abhikoreti** [comment]
Integrated Swagger UI for these APIs. Made some changes in the server.js and swagger.js to run the app on vercel. 

- Added customJs and customCssUrl in swagger.js
- set `require("./swagger")(app);` before `app.listen`, as it was unable to go on swagger.js
- Added a `BASEURL` variable in `.env` file to point to that url

**Comment by omssp** [comment]
Adding an [example](https://api.redislabs.com/v1/swagger-ui/index.html) of swagger api docs page.
 - Find and integrate the mechanisms of "Authorize" button on the page such that `x-access-token` can be directly used all at once
 - The example also has segments/sections - with short descriptions _(e.g. Account Current account and ownership)_ : Use similar structure of sections

**Comment by abhikoreti** [comment]
Added the authorize button that takes `x-access-token` one time and can be used to authenticate for valid token for each api endpoint.

- In swagger.js, added a securityScheme as `type: apiKey` to allow custom access tokens with scheme name as `bearerAuth`. (example can be found on [Official Documentation](https://swagger.io/docs/specification/authentication/bearer-authentication/))
- Use this `bearerAuth` locally for each api request in their respective routes or can be declared globally in swagger file itself for all api endpoints.
